"""
Build the single self-contained HTML deliverable from outputs/loops.json.
No external deps, no CDN, no build step — opens by double-click. Data is baked
in as a JS object generated by the run.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
data = json.loads((ROOT / "outputs" / "loops.json").read_text())


def norm_family(w):
    name = w["name"].lower()
    fam = (w.get("family") or "").lower()
    rfp = w["evidence"]["qual"].get("rfp_which", "").lower()
    if fam == "precision-ag" or any(k in name for k in ["orchard", "farm", "crop", "weed"]):
        return "precision-ag"
    if "lab" in fam or "lab" in name:
        return "autonomous-labs"
    if any(k in fam + name for k in ["drone", "interceptor", "swarm"]):
        return "counter-drone"
    if "data-crusade" in rfp and any(k in name for k in ["infra", "roboloop"]):
        return "robotics-infra"
    return "industrial-arms"


# normalize + pick top 3 distinct families by (projected, today, -loop)
for w in data["wedges"]:
    w["norm_family"] = norm_family(w)
ranked = sorted(data["wedges"],
                key=lambda w: (w["scores"]["projected_score"],
                               w["scores"]["today_score"], -w["loop"]), reverse=True)
top3, seen = [], set()
for w in ranked:
    if w["norm_family"] in seen:
        continue
    seen.add(w["norm_family"])
    top3.append(w)
    if len(top3) == 3:
        break
data["top3_ids"] = [w["id"] for w in top3]
data["top3_selection"] = ("best wedge per normalized family, ranked by projected "
                          "score, so the Top 3 are 3 genuinely distinct wedges")

# persist normalized families + corrected top3 back to the audit file so
# loops.json, the HTML, and the console summary all agree
(ROOT / "outputs" / "loops.json").write_text(json.dumps(data, indent=2))

js = json.dumps(data, indent=None, separators=(",", ":"))

HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Pong Academy — Antler Wedge Finder</title>
<style>
  :root{
    --bg:#0a0e14; --panel:#141b27; --panel2:#10151f; --line:#2a3852;
    --ink:#f4f8fc; --mut:#b4c0d2; --dim:#8593a6;
    --today:#ffb04d; --proj:#4ae8a6; --acc:#73b4ff; --bad:#ff6b79; --warn:#ffd569;
    --mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
    --sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  }
  *{box-sizing:border-box}
  html{scroll-behavior:smooth}
  body{margin:0;background:radial-gradient(1200px 700px at 70% -10%,#15233a 0%,var(--bg) 55%);
       color:var(--ink);font-family:var(--sans);line-height:1.55;-webkit-font-smoothing:antialiased}
  a{color:var(--acc);text-decoration:none}
  .wrap{max-width:1080px;margin:0 auto;padding:0 22px}
  h1,h2,h3{line-height:1.15;margin:0}
  .mono{font-family:var(--mono)}
  .mut{color:var(--mut)} .dim{color:var(--dim)}

  /* ---------- HERO ---------- */
  .hero{min-height:100vh;display:flex;flex-direction:column;justify-content:center;
        align-items:center;text-align:center;position:relative;overflow:hidden}
  .hero .kicker{font-family:var(--mono);font-size:12px;letter-spacing:.32em;color:var(--acc);
        text-transform:uppercase;opacity:0;transform:translateY(10px);animation:rise .8s .2s forwards}
  .hero h1{font-size:clamp(34px,6vw,64px);font-weight:800;margin:0 0 8px;letter-spacing:-.02em;
        opacity:0;transform:translateY(14px);animation:rise .9s .25s forwards}
  .hero h1 .am{color:var(--today)}
  .hero .sub{max-width:680px;color:var(--mut);font-size:clamp(15px,2vw,18px);
        opacity:0;animation:fade 1s 1s forwards}
  .flow{display:flex;gap:18px;margin:54px 0 10px;flex-wrap:wrap;justify-content:center}
  .stage{width:268px;max-width:86vw;background:linear-gradient(180deg,var(--panel),var(--panel2));
        border:1px solid var(--line);border-radius:16px;padding:22px 20px;text-align:left;
        opacity:0;transform:translateY(26px) scale(.97);position:relative}
  .stage.in{animation:pop .7s cubic-bezier(.2,.8,.2,1) forwards}
  .stage .n{font-family:var(--mono);font-size:12px;color:var(--dim)}
  .stage h3{font-size:19px;margin:6px 0 8px}
  .stage p{margin:0;color:var(--mut);font-size:13.5px}
  .stage .bar{height:4px;border-radius:3px;margin-top:14px;width:0;
        background:linear-gradient(90deg,var(--acc),var(--proj))}
  .stage.in .bar{animation:grow .9s .25s forwards}
  .arrow{align-self:center;color:var(--dim);font-size:24px;opacity:0}
  .arrow.in{animation:fade .5s forwards}
  .s1.in{border-color:#6ea8ff55} .s2.in{border-color:#f2a23c55} .s3.in{border-color:#3ddc9755}
  .scrolldn{position:absolute;bottom:26px;color:var(--dim);font-size:12px;letter-spacing:.2em;
        opacity:0;animation:fade 1s 2.6s forwards}
  @keyframes rise{to{opacity:1;transform:none}}
  @keyframes fade{to{opacity:1}}
  @keyframes pop{to{opacity:1;transform:none}}
  @keyframes grow{to{width:100%}}

  /* ---------- SCREEN base ---------- */
  .screen{min-height:100vh;display:flex;flex-direction:column;justify-content:center;
        align-items:center;position:relative;overflow:hidden;padding:64px 0}

  /* ---------- SCREEN 1 · BRAND + VIDEO ---------- */
  .brand{text-align:center}
  .brandmark{display:flex;align-items:center;gap:14px;justify-content:center;
        opacity:0;transform:translateY(12px);animation:rise .8s .15s forwards}
  .brandmark .dot{width:46px;height:46px;border-radius:50%;flex:none;position:relative;
        background:radial-gradient(circle at 32% 30%,#fff 0 18%,var(--today) 19% 52%,#b9701f 53% 100%);
        box-shadow:0 0 0 4px rgba(255,176,77,.12),0 8px 30px rgba(255,176,77,.25)}
  .brandmark .dot:after{content:"";position:absolute;inset:0;border-radius:50%;
        border:1px solid rgba(255,255,255,.35)}
  .brandmark h1{font-size:clamp(38px,7vw,76px);font-weight:800;letter-spacing:-.03em;line-height:1}
  .brandmark h1 span{color:var(--today)}
  .brandbullets{list-style:none;padding:0;margin:26px 0 0;display:flex;gap:12px;
        flex-wrap:wrap;justify-content:center;opacity:0;animation:fade 1s .8s forwards}
  .brandbullets li{font-family:var(--mono);font-size:clamp(12px,1.5vw,15px);letter-spacing:.06em;
        color:var(--ink);border:1px solid var(--line);background:rgba(255,255,255,.03);
        border-radius:30px;padding:9px 18px;display:inline-flex;align-items:center;gap:9px}
  .brandbullets li:before{content:"";width:7px;height:7px;border-radius:2px;background:var(--today)}
  .videoframe{width:min(1000px,92vw);margin:42px auto 0;border:1px solid var(--line);border-radius:16px;
        overflow:hidden;background:#05080d;aspect-ratio:16/9;position:relative;
        box-shadow:0 30px 80px rgba(0,0,0,.5);opacity:0;transform:translateY(20px);
        animation:rise 1s 1.1s forwards}
  .videoframe video{width:100%;height:100%;object-fit:cover;display:block}
  .videoframe .vtag{position:absolute;left:14px;top:12px;z-index:2;font-family:var(--mono);
        font-size:11px;letter-spacing:.18em;color:var(--ink);background:rgba(5,8,13,.6);
        border:1px solid var(--line);border-radius:20px;padding:4px 11px;backdrop-filter:blur(3px)}

  /* ---------- SCREEN 2 · HOW IT WORKS (blueprint) ---------- */
  .bp{--bp:#0b3a6f;--bp-deep:#072a52;--bink:#e8f1ff;--bink-dim:#a9c8f5;--bamber:#ffd54a;
      --bline:rgba(150,190,255,.20);--bline2:rgba(190,215,255,.55);
      background:radial-gradient(120% 100% at 50% 0%,#0e4685 0%,var(--bp) 45%,var(--bp-deep) 100%);
      color:var(--bink);font-family:var(--mono)}
  .bp:before{content:"";position:absolute;inset:0;pointer-events:none;
      background-image:linear-gradient(var(--bline) 1px,transparent 1px),
        linear-gradient(90deg,var(--bline) 1px,transparent 1px),
        linear-gradient(var(--bline2) 1px,transparent 1px),
        linear-gradient(90deg,var(--bline2) 1px,transparent 1px);
      background-size:26px 26px,26px 26px,130px 130px,130px 130px;
      mask-image:radial-gradient(130% 110% at 50% 45%,#000 60%,transparent 100%)}
  .bp .bpframe{position:absolute;inset:18px;border:1.5px solid var(--bline2);z-index:2;pointer-events:none}
  .bp .bpframe i{position:absolute;width:14px;height:14px;border:1.5px solid var(--bink)}
  .bp .bpframe i.tl{top:-1px;left:-1px;border-right:none;border-bottom:none}
  .bp .bpframe i.tr{top:-1px;right:-1px;border-left:none;border-bottom:none}
  .bp .bpframe i.bl{bottom:-1px;left:-1px;border-right:none;border-top:none}
  .bp .bpframe i.br{bottom:-1px;right:-1px;border-left:none;border-top:none}
  .bp .bpstage{position:relative;z-index:3;width:100%;display:flex;justify-content:center}
  .bp svg{width:min(1180px,94vw);height:auto;display:block}
  .bp text{font-family:var(--mono)}
  .bp .lbl{fill:var(--bink);font-size:21px;letter-spacing:1px}
  .bp .lbl-sm{fill:var(--bink);font-size:15px;letter-spacing:.5px}
  .bp .lbl-sub{fill:var(--bink-dim);font-size:11px;letter-spacing:1px}
  .bp .tag{fill:var(--bamber);font-size:13px;letter-spacing:2px;font-weight:700}
  .bp .title{fill:var(--bink);font-size:28px;letter-spacing:3px;font-weight:800}
  .bp .title-rule{stroke:var(--bamber);stroke-width:1.5}
  .bp .node{fill:rgba(10,52,100,.35);stroke:var(--bink);stroke-width:1.5}
  .bp .edge{fill:none;stroke:var(--bink);stroke-width:1.6}
  .bp .edge-loop{fill:none;stroke:var(--bamber);stroke-width:1.8;stroke-dasharray:6 5}
  .bp .edge-fan{fill:none;stroke:var(--bink-dim);stroke-width:1.4}
  .bp .draw{stroke-dasharray:1400;stroke-dashoffset:1400}
  .bp.go .draw{animation:bpdraw 1.2s ease forwards}
  .bp.go .draw.d1{animation-delay:.1s}.bp.go .draw.d2{animation-delay:.4s}
  .bp.go .draw.d3{animation-delay:.7s}.bp.go .draw.d4{animation-delay:1s}
  @keyframes bpdraw{to{stroke-dashoffset:0}}
  .bp .pop{opacity:0}
  .bp.go .pop{animation:bppop .5s ease forwards}
  .bp.go .p1{animation-delay:.2s}.bp.go .p2{animation-delay:.5s}.bp.go .p3{animation-delay:.8s}
  .bp.go .p4{animation-delay:1.2s}.bp.go .p5{animation-delay:1.5s}.bp.go .p6{animation-delay:1.7s}.bp.go .p7{animation-delay:1.9s}
  @keyframes bppop{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}
  .bp .loop-flow{animation:bpflow 1.4s linear infinite}
  @keyframes bpflow{to{stroke-dashoffset:-22}}

  /* ---------- HERO autoresearch loop ---------- */
  .loopwrap{width:min(840px,94vw);margin:8px auto 0;opacity:0;animation:fade 1.1s 2.2s forwards}
  .loopwrap svg{width:100%;height:auto;display:block;overflow:visible}
  .aredge{fill:none;stroke:var(--today);stroke-width:2;stroke-dasharray:7 6}
  .aredge.flow{animation:lflow 1.25s linear infinite}
  @keyframes lflow{to{stroke-dashoffset:-26}}
  .arlabel{fill:var(--today);font-family:var(--mono);font-size:12px;letter-spacing:.24em}
  @media(max-width:872px){.loopwrap{display:none}}

  /* ---------- SECTIONS ---------- */
  section.block{padding:64px 0 12px}
  .eyebrow{font-family:var(--mono);font-size:12px;letter-spacing:.28em;color:var(--acc);
        text-transform:uppercase;margin-bottom:10px}
  h2.title{font-size:clamp(24px,3.4vw,34px);font-weight:800;letter-spacing:-.01em;margin-bottom:6px}
  .lead{color:var(--mut);max-width:760px;margin-bottom:22px}

  /* top3 cards */
  .cards{display:grid;grid-template-columns:1fr;gap:16px}
  @media(min-width:840px){.cards{grid-template-columns:repeat(3,1fr)}}
  .card{background:linear-gradient(180deg,var(--panel),var(--panel2));border:1px solid var(--line);
        border-radius:16px;padding:20px;position:relative;overflow:hidden}
  .rankpill{position:absolute;top:14px;right:14px;font-family:var(--mono);font-size:11px;
        color:var(--dim);border:1px solid var(--line);border-radius:20px;padding:3px 9px}
  .card .fam{font-family:var(--mono);font-size:11px;color:var(--acc);letter-spacing:.1em;text-transform:uppercase}
  .card h3{font-size:19px;margin:8px 0}
  .card .tag{color:var(--mut);font-size:13.5px;min-height:38px}
  .scrow{display:flex;gap:10px;margin:14px 0 4px}
  .scbox{flex:1;border:1px solid var(--line);border-radius:11px;padding:9px 11px;background:#0c1119}
  .scbox .lab{font-size:10.5px;letter-spacing:.12em;text-transform:uppercase}
  .scbox .v{font-family:var(--mono);font-size:25px;font-weight:700;line-height:1.1}
  .scbox.t .v{color:var(--today)} .scbox.p .v{color:var(--proj)}
  .scbox.t .lab{color:var(--today)} .scbox.p .lab{color:var(--proj)}
  ul.b{list-style:none;padding:0;margin:12px 0 0}
  ul.b li{font-size:13px;margin:9px 0;padding-left:16px;position:relative;color:#dde6f1}
  ul.b li:before{content:"";position:absolute;left:0;top:8px;width:6px;height:6px;border-radius:2px;background:var(--acc)}
  ul.b li b{color:var(--ink);font-weight:600}

  /* detail */
  .detail{background:linear-gradient(180deg,var(--panel),var(--panel2));border:1px solid var(--line);
        border-radius:18px;padding:26px;margin:18px 0}
  .detail .head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;flex-wrap:wrap}
  .detail h3{font-size:23px}
  .detail .tagline{color:var(--mut);margin-top:6px;max-width:680px}
  .bandtag{font-family:var(--mono);font-size:11px;border-radius:6px;padding:3px 8px;border:1px solid var(--line);color:var(--mut)}
  .grid2{display:grid;grid-template-columns:1fr;gap:20px;margin-top:18px}
  @media(min-width:820px){.grid2{grid-template-columns:1.05fr .95fr}}
  .schema{display:grid;grid-template-columns:1fr;gap:0}
  .frow{padding:9px 0;border-bottom:1px dashed var(--line)}
  .frow:last-child{border-bottom:0}
  .frow .k{font-family:var(--mono);font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:var(--dim)}
  .frow .val{font-size:13.5px;color:#e6edf6;margin-top:2px}

  /* criterion bars */
  .bars{margin-top:2px}
  .crit{margin:0 0 9px}
  .crit .cl{display:flex;justify-content:space-between;font-size:12px;margin-bottom:3px}
  .crit .cl .nm{color:#dde6f1} .crit .cl .nm small{color:var(--dim);font-family:var(--mono)}
  .crit .cl .pp{font-family:var(--mono);color:var(--mut)}
  .track{position:relative;height:13px;background:#0c1119;border:1px solid var(--line);border-radius:7px;overflow:hidden}
  .fill{position:absolute;top:0;left:0;height:100%;border-radius:6px;width:0;transition:width 1.1s cubic-bezier(.2,.8,.2,1)}
  .fill.today{background:linear-gradient(90deg,#b9701f,var(--today));opacity:.95;z-index:2}
  .fill.proj{background:linear-gradient(90deg,#1f9c69,var(--proj));opacity:.45;z-index:1}
  .legend{display:flex;gap:16px;font-size:12px;color:var(--mut);margin:4px 0 10px}
  .legend span{display:inline-flex;align-items:center;gap:6px}
  .sw{width:12px;height:12px;border-radius:3px;display:inline-block}
  .totline{display:flex;gap:10px;margin-top:8px}
  .totline .tt{flex:1;text-align:center;border:1px solid var(--line);border-radius:10px;padding:7px}
  .totline .tt .v{font-family:var(--mono);font-size:20px;font-weight:700}

  /* gates */
  .gates{display:flex;flex-wrap:wrap;gap:8px;margin-top:6px}
  .gate{font-family:var(--mono);font-size:11px;border-radius:7px;padding:5px 9px;border:1px solid var(--line)}
  .gate.pass{color:var(--proj);border-color:#1f5e44}
  .gate.at_risk{color:var(--warn);border-color:#6b5a1f}
  .gate.fail{color:var(--bad);border-color:#6b2530}
  .exp{border:1px solid var(--line);border-left:3px solid var(--acc);border-radius:10px;
       padding:13px 15px;margin-top:14px;background:#0c1119}
  .exp .k{font-family:var(--mono);font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:var(--acc)}
  .gng{margin-top:8px;font-family:var(--mono);font-size:13px;color:var(--proj)}
  .pitch{margin-top:14px;font-style:italic;color:#dde6f1;border-top:1px solid var(--line);padding-top:12px}

  /* loops table */
  table{width:100%;border-collapse:collapse;font-size:13px;margin-top:6px}
  th,td{text-align:left;padding:9px 10px;border-bottom:1px solid var(--line)}
  th{font-family:var(--mono);font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:var(--dim)}
  td.mono,th.r{text-align:right} td.r{text-align:right;font-family:var(--mono)}
  tr.kept{background:rgba(61,220,151,.05)}
  .stat{font-family:var(--mono);font-size:11px;border-radius:6px;padding:2px 7px;border:1px solid var(--line)}
  .stat.keep{color:var(--proj);border-color:#1f5e44}
  .stat.base{color:var(--acc);border-color:#264a73}
  .stat.disc{color:var(--mut)}
  .delta.pos{color:var(--proj)} .delta.neg{color:var(--bad)}

  /* verdict */
  .verdict{background:linear-gradient(180deg,#161c12,#0f140c);border:1px solid #3a4a24;
        border-radius:18px;padding:26px}
  .verdict.no{background:linear-gradient(180deg,#1c1417,#140c0e);border-color:#5a2a30}
  .verdict h2{font-size:22px;margin-bottom:8px}
  .verdict .big{font-family:var(--mono);font-size:14px;color:var(--warn);margin-bottom:12px}
  .verdict p{color:#e6edf6;margin:0 0 10px}
  .verdict .path{border-top:1px solid var(--line);padding-top:12px;margin-top:6px}

  footer{padding:40px 0 60px;color:var(--dim);font-size:12px;text-align:center}
  .meta{font-family:var(--mono);font-size:11px;color:var(--dim);margin-top:6px;word-break:break-all}
  .reveal{opacity:0;transform:translateY(20px)}
  .reveal.in{opacity:1;transform:none;transition:opacity .7s,transform .7s}
</style>
</head>
<body>

<!-- ===== SCREEN 1 · BRAND + VIDEO ===== -->
<section class="screen brand">
  <div class="wrap">
    <div class="brandmark">
      <span class="dot"></span>
      <h1>Pong&nbsp;<span>Academy</span></h1>
    </div>
    <ul class="brandbullets">
      <li>Last-Mile Calibration for Edge Devices</li>
      <li>Powered by Autoresearch</li>
      <li>Available by MCP</li>
    </ul>
    <div class="videoframe">
      <span class="vtag">LIVE RIG · DEMO</span>
      <video autoplay muted loop playsinline preload="auto">
        <source src="data:video/mp4;base64,__VIDEO__" type="video/mp4">
      </video>
    </div>
  </div>
  <div class="scrolldn">SCROLL ↓</div>
</section>

<!-- ===== SCREEN 2 · HOW IT WORKS (blueprint) ===== -->
<section class="screen bp" id="howitworks">
  <div class="bpframe"><i class="tl"></i><i class="tr"></i><i class="bl"></i><i class="br"></i></div>
  <div class="bpstage">
    <svg viewBox="0 0 1180 768" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <marker id="arr" markerWidth="11" markerHeight="11" refX="8" refY="5" orient="auto">
          <path d="M1,1 L9,5 L1,9" fill="none" stroke="var(--bink)" stroke-width="1.6"/></marker>
        <marker id="arrA" markerWidth="11" markerHeight="11" refX="8" refY="5" orient="auto">
          <path d="M1,1 L9,5 L1,9" fill="none" stroke="var(--bamber)" stroke-width="1.6"/></marker>
        <marker id="arrD" markerWidth="11" markerHeight="11" refX="8" refY="5" orient="auto">
          <path d="M1,1 L9,5 L1,9" fill="none" stroke="var(--bink-dim)" stroke-width="1.4"/></marker>
      </defs>
      <text class="title pop p1" x="590" y="46" text-anchor="middle">HOW PONG ACADEMY WORKS</text>
      <line class="title-rule pop p1" x1="330" y1="62" x2="850" y2="62"/>
      <g class="pop p2">
        <rect class="node" x="490" y="100" width="200" height="60" rx="3"/>
        <text class="lbl-sm" x="590" y="130" text-anchor="middle">EPISODE MEMORY</text>
        <text class="lbl-sub" x="590" y="150" text-anchor="middle">PRIOR RUNS · CONTEXT</text>
      </g>
      <path class="edge draw d2" d="M590,160 L590,196" marker-end="url(#arr)"/>
      <g class="pop p3">
        <rect class="node" x="60" y="200" width="200" height="64" rx="3"/>
        <text class="lbl" x="160" y="232" text-anchor="middle">CAMERA</text>
        <text class="lbl-sub" x="160" y="252" text-anchor="middle">VISION INPUT</text>
      </g>
      <g class="pop p3">
        <rect class="node" x="490" y="200" width="200" height="64" rx="3"/>
        <text class="lbl" x="590" y="232" text-anchor="middle">RASPBERRY Pi</text>
        <text class="lbl-sub" x="590" y="252" text-anchor="middle">EDGE COMPUTE</text>
      </g>
      <g class="pop p3">
        <rect class="node" x="920" y="200" width="200" height="64" rx="3"/>
        <text class="lbl" x="1020" y="232" text-anchor="middle">ACTION</text>
        <text class="lbl-sub" x="1020" y="252" text-anchor="middle">ACTUATION</text>
      </g>
      <path class="edge draw d1" d="M260,232 L482,232" marker-end="url(#arr)"/>
      <path class="edge draw d2" d="M690,232 L912,232" marker-end="url(#arr)"/>
      <text class="tag pop p4" x="590" y="328" text-anchor="middle">AUTORESEARCH LOOP</text>
      <g class="pop p4"><path class="edge-loop loop-flow" d="M1020,264 L1020,355 L160,355 L160,268" marker-end="url(#arrA)"/></g>
      <g class="pop p4">
        <rect class="node" x="470" y="400" width="240" height="70" rx="3"/>
        <text class="lbl" x="590" y="433" text-anchor="middle">MCP SERVER</text>
        <text class="lbl-sub" x="590" y="454" text-anchor="middle">MODEL CONTEXT PROTOCOL</text>
      </g>
      <path class="edge-fan draw d3" d="M590,355 L590,398"/>
      <path class="edge-fan draw d4" d="M520,470 L235,620" marker-end="url(#arrD)"/>
      <path class="edge-fan draw d4" d="M590,470 L590,620" marker-end="url(#arrD)"/>
      <path class="edge-fan draw d4" d="M660,470 L945,620" marker-end="url(#arrD)"/>
      <g class="pop p5">
        <rect class="node" x="55" y="628" width="280" height="92" rx="3"/>
        <text class="lbl-sm" x="195" y="662" text-anchor="middle">SMART HOME</text>
        <text class="lbl-sm" x="195" y="684" text-anchor="middle">APPLIANCE</text>
        <text class="lbl-sub" x="195" y="706" text-anchor="middle">PERSONALIZATION</text>
      </g>
      <g class="pop p6">
        <rect class="node" x="450" y="628" width="280" height="92" rx="3"/>
        <text class="lbl-sm" x="590" y="662" text-anchor="middle">ADAPTIVE SPORTS</text>
        <text class="lbl-sm" x="590" y="684" text-anchor="middle">TRAINING</text>
        <text class="lbl-sub" x="590" y="706" text-anchor="middle">MOTION COACHING</text>
      </g>
      <g class="pop p7">
        <rect class="node" x="845" y="628" width="280" height="92" rx="3"/>
        <text class="lbl-sm" x="985" y="662" text-anchor="middle">PRECISION</text>
        <text class="lbl-sm" x="985" y="684" text-anchor="middle">AGRICULTURE</text>
        <text class="lbl-sub" x="985" y="706" text-anchor="middle">CROP MONITORING</text>
      </g>
      <text class="lbl-sub" x="590" y="752" text-anchor="middle" opacity=".75">— EDGE-CASE DEPLOYMENTS —</text>
    </svg>
  </div>
  <div class="scrolldn">SCROLL ↓</div>
</section>

<div class="hero">
  <div class="wrap">
    <h1>Pong <span class="am">Academy</span> → <span class="am">the Antler Wedge</span></h1>
    <div class="flow" id="flow">
      <div class="stage s1" id="st1">
        <div class="n">STAGE 01</div><h3>Founder–Market Fit</h3>
        <p>A rare GTM + perception pair: Aleh (7× founder, 2 exits, ships paying products in days) × Ed (CMU robotics; JPL / Saronic / Andromeda perception).</p>
        <div class="bar"></div>
      </div>
      <div class="arrow" id="ar1">→</div>
      <div class="stage s2" id="st2">
        <div class="n">STAGE 02</div><h3>Product–Market Fit</h3>
        <p>Match the mechanic — a constrained, measurable action loop in a highly variable real world — to a beachhead where the sim-to-real gap is paid for in human engineering hours.</p>
        <div class="bar"></div>
      </div>
      <div class="arrow" id="ar2">→</div>
      <div class="stage s3" id="st3">
        <div class="n">STAGE 03</div><h3>Antler Selection Criteria</h3>
        <p>10 weighted criteria, 5 hard gates, today vs projected. Frozen scorer the agent can never edit to win.</p>
        <div class="bar"></div>
      </div>
    </div>
    <div class="loopwrap" aria-hidden="true">
      <svg viewBox="0 0 840 116" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <marker id="arL" markerWidth="11" markerHeight="11" refX="7" refY="5" orient="auto">
            <path d="M1,1 L9,5 L1,9" fill="none" stroke="var(--today)" stroke-width="1.8"/>
          </marker>
        </defs>
        <path class="aredge flow"
              d="M706,4 L706,66 Q706,86 686,86 L154,86 Q134,86 134,66 L134,12"
              marker-end="url(#arL)"/>
        <text class="arlabel" x="420" y="80" text-anchor="middle">AUTORESEARCH LOOP</text>
      </svg>
    </div>
  </div>
  <div class="scrolldn">SCROLL ↓</div>
</div>

<div class="wrap">
  <section class="block reveal" id="top3sec">
    <div class="eyebrow">The Result</div>
    <h2 class="title">Top 3 Wedges</h2>
    <p class="lead">Ranked by projected Antler score (after the single 4-week validating experiment succeeds), selected as three genuinely distinct wedge families.</p>
    <div class="cards" id="cards"></div>
  </section>

  <section class="block reveal" id="detailsec">
    <div class="eyebrow">Under the Hood</div>
    <h2 class="title">Per-Wedge Detail</h2>
    <p class="lead">Full filled Antler schema · today vs projected per-criterion breakdown · gates at risk · the one 4-week experiment with an explicit go/no-go · why pitch Antler.</p>
    <div id="details"></div>
  </section>

  <section class="block reveal" id="loopsec">
    <div class="eyebrow">Audit Trail</div>
    <h2 class="title">All Autoresearch Loops</h2>
    <p class="lead">Every propose→score→keep/rollback iteration. Champion advances only when a proposal's projected score beats it; otherwise the branch rolls back.</p>
    <div id="loops"></div>
  </section>

  <section class="block reveal" id="verdictsec">
    <div class="eyebrow">The Honest Read</div>
    <h2 class="title">Verdict</h2>
    <div id="verdict"></div>
  </section>
</div>

<footer>
  <div>Pong Academy · Antler Wedge Finder — generated by a frozen-evaluator Autoresearch run.</div>
  <div class="meta" id="meta"></div>
</footer>

<script>
const DATA = __DATA__;

/* ---------- hero sequence ---------- */
const seq = [["st1",250],["ar1",1050],["st2",1300],["ar2",2100],["st3",2350]];
seq.forEach(([id,t])=>setTimeout(()=>document.getElementById(id).classList.add("in"),t));

/* ---------- helpers ---------- */
const byId = id => DATA.wedges.find(w=>w.id===id);
const esc = s => (s==null?"":String(s)).replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));
const top3 = DATA.top3_ids.map(byId);
const GATE_NAMES = {
  G1_founder_market_fit:"Founder–market fit",
  G2_problem_solution_fit:"Problem–solution fit",
  G3_validation_beyond_vision:"Validation beyond vision",
  G4_scalable_outcome:"Scalable venture outcome",
  G5_compelling_story:"Compelling story"
};

/* ---------- top 3 cards ---------- */
document.getElementById("cards").innerHTML = top3.map((w,i)=>{
  const s=w.scores;
  return `<div class="card">
    <div class="rankpill">#${i+1} · ${esc(w.id)}</div>
    <div class="fam">${esc(w.norm_family)}</div>
    <h3>${esc(w.name)}</h3>
    <div class="tag">${esc(w.tagline)}</div>
    <div class="scrow">
      <div class="scbox t"><div class="lab">Today</div><div class="v">${s.today_score}</div></div>
      <div class="scbox p"><div class="lab">Projected</div><div class="v">${s.projected_score}</div></div>
    </div>
    <ul class="b">
      <li><b>Problem.</b> ${esc(w.problem)}</li>
      <li><b>Solution.</b> ${esc(w.mvp_plan)}</li>
      <li><b>Why now.</b> ${esc(w.why_now)}</li>
    </ul>
  </div>`;
}).join("");

/* ---------- per-wedge detail ---------- */
function critBars(w){
  const tb=w.scores.today.breakdown, pb=w.scores.projected.breakdown;
  const order=Object.keys(DATA.meta.weights);
  return order.map(k=>{
    const wt=DATA.meta.weights[k], lbl=DATA.meta.criteria_labels[k];
    const tp=tb[k].points, pp=pb[k].points;
    const tpc=(tp/wt*100), ppc=(pp/wt*100);
    return `<div class="crit">
      <div class="cl"><span class="nm">${esc(lbl)} <small>· w${wt}</small></span>
        <span class="pp"><span style="color:var(--today)">${tp.toFixed(1)}</span> / <span style="color:var(--proj)">${pp.toFixed(1)}</span></span></div>
      <div class="track">
        <div class="fill proj" data-w="${ppc}"></div>
        <div class="fill today" data-w="${tpc}"></div>
      </div></div>`;
  }).join("");
}
function schemaRows(w){
  const rows=[
    ["ICP / beachhead",w.icp],["Painful problem",w.problem],["Why now",w.why_now],
    ["Demand evidence (3rd-party pull)",w.demand_evidence],["MVP plan",w.mvp_plan],
    ["Market + expansion",w.market_expansion],["Defensibility / moat",w.defensibility],
    ["Business model + unit economics",w.business_model],
    ["Founder–market fit (real facts)",w.evidence.qual.founder_fit_justification]
  ];
  return rows.map(([k,v])=>`<div class="frow"><div class="k">${esc(k)}</div><div class="val">${esc(v)}</div></div>`).join("");
}
function gatesRow(w){
  const g=w.scores.today.gates;
  return Object.keys(g).map(k=>`<span class="gate ${g[k]}">${esc(GATE_NAMES[k])}: ${g[k].replace("_"," ")}</span>`).join("");
}
document.getElementById("details").innerHTML = top3.map((w,i)=>{
  const s=w.scores;
  return `<div class="detail" data-detail>
    <div class="head">
      <div><h3>#${i+1} · ${esc(w.name)} <span class="dim mono">(${esc(w.id)})</span></h3>
        <div class="tagline">${esc(w.tagline)}</div></div>
      <div style="text-align:right">
        <div class="bandtag">today ${s.today_score} · ${esc(s.band_today)}</div><br>
        <div class="bandtag" style="margin-top:5px;color:var(--proj)">projected ${s.projected_score} · ${esc(s.band_projected)}</div>
      </div>
    </div>
    <div class="grid2">
      <div class="schema">${schemaRows(w)}</div>
      <div>
        <div class="legend">
          <span><span class="sw" style="background:var(--today)"></span>Today (now)</span>
          <span><span class="sw" style="background:var(--proj);opacity:.55"></span>Projected (post-experiment)</span>
        </div>
        <div class="bars">${critBars(w)}</div>
        <div class="totline">
          <div class="tt"><div class="dim" style="font-size:11px">TODAY</div><div class="v" style="color:var(--today)">${s.today_score}</div></div>
          <div class="tt"><div class="dim" style="font-size:11px">PROJECTED</div><div class="v" style="color:var(--proj)">${s.projected_score}</div></div>
        </div>
        <div style="margin-top:14px"><div class="frow"><div class="k">Hard gates — status today</div></div>
          <div class="gates">${gatesRow(w)}</div></div>
      </div>
    </div>
    <div class="exp">
      <div class="k">The single 4-week validating experiment</div>
      <div class="val" style="margin-top:5px">${esc(w.experiment_4wk)}</div>
      <div class="gng">GO / NO-GO → ${esc(w.go_no_go)}</div>
    </div>
    <div class="pitch">“${esc(w.why_pitch_antler)}”</div>
  </div>`;
}).join("");

/* ---------- loops table ---------- */
const rows = DATA.loops.map(l=>{
  const st = l.status.startsWith("keep")?"keep":(l.status.startsWith("baseline")?"base":"disc");
  const stl = l.status.startsWith("keep")?"keep":(l.status.startsWith("baseline")?"baseline":"rolled back");
  const d = l.delta_vs_parent;
  const dtxt = d==null?"—":(d>0?`+${d}`:`${d}`);
  const dcl = d==null?"":(d>0?"pos":(d<0?"neg":""));
  return `<tr class="${st==='keep'||st==='base'?'kept':''}">
    <td class="mono dim">${esc(l.id)}</td>
    <td>${esc(l.name)} <span class="dim mono" style="font-size:11px">${l.kind==='mutate'?'· mutate '+esc(l.parent||''):'· seed'}</span></td>
    <td class="r" style="color:var(--today)">${l.today_score}</td>
    <td class="r" style="color:var(--proj)">${l.projected_score}</td>
    <td class="r delta ${dcl}">${dtxt}</td>
    <td><span class="stat ${st}">${stl}</span></td>
  </tr>`;
}).join("");
document.getElementById("loops").innerHTML = `<table>
  <thead><tr><th>ID</th><th>Wedge</th><th class="r">Today</th><th class="r">Projected</th><th class="r">Δ vs parent</th><th>Result</th></tr></thead>
  <tbody>${rows}</tbody></table>`;

/* ---------- verdict ---------- */
const v = DATA.verdict;
const clears = v.any_candidate_clears_70_today;
const champ = top3[0];
document.getElementById("verdict").innerHTML = `
  <div class="verdict ${clears?'':'no'}">
    <h2>Does any candidate clear the 70+ “potentially fundable” band <u>today</u>?</h2>
    <div class="big">${clears?'YES':'NO'} — best today = ${v.best_today_score} (${esc(v.best_today_name)}), short of 70.</div>
    <p>Across all ${DATA.loops.length} loops, the frozen evaluator put every candidate in the <b>55–69 “interesting but under-validated”</b> band today. The reason is structural and honest: founder–market fit, market size, why-now and the architectural moat all score well on reasoning, but the heaviest-weighted criterion — <b>Evidence of demand (18 pts)</b> — sits near its floor, and the validation hard gate (<b>G3: validation beyond vision</b>) <b>fails for every wedge today</b> because there is not yet a single paying customer, pilot, LOI, or design partner. The VC RFPs supply reputable third-party pull, but that is not the same as a buyer signing.</p>
    <div class="path">
      <p><b>The single fastest path across the line:</b> run the #1 wedge's 4-week experiment now — <b>${esc(champ.name)}</b>. ${esc(champ.experiment_4wk)} Hitting its go/no-go (<span class="mono" style="color:var(--proj)">${esc(champ.go_no_go)}</span>) converts G2 and G3 from fail/at-risk to pass and moves <b>Evidence of demand</b> off the floor — which is exactly the jump from <b>${champ.scores.today_score} today to a projected ${champ.scores.projected_score}</b>. One signed design partner is worth more than another month of deck-polishing.</p>
    </div>
  </div>`;

/* ---------- meta + reveals ---------- */
document.getElementById("meta").innerHTML =
  `model: ${esc(DATA.meta.proposer_model)} · loops: ${DATA.meta.n_loops} · generated: ${esc(DATA.meta.generated)}<br>frozen evaluator SHA-256: ${esc(DATA.meta.frozen_evaluator_sha256)}`;

const io = new IntersectionObserver(es=>es.forEach(e=>{
  if(e.isIntersecting){
    e.target.classList.add("in");
    e.target.querySelectorAll(".fill").forEach(f=>f.style.width=f.dataset.w+"%");
    io.unobserve(e.target);
  }
}),{threshold:.12});
document.querySelectorAll(".reveal").forEach(el=>io.observe(el));
document.querySelectorAll("[data-detail]").forEach(el=>io.observe(el));

/* blueprint (How it Works) draw-in when scrolled into view */
const bpio = new IntersectionObserver(es=>es.forEach(e=>{
  if(e.isIntersecting){ e.target.classList.add("go"); bpio.unobserve(e.target); }
}),{threshold:.2});
document.querySelectorAll(".bp").forEach(el=>bpio.observe(el));
</script>
</body>
</html>
"""

import base64
video_path = ROOT / "engine" / "assets" / "Demo_web.mp4"
video_b64 = base64.b64encode(video_path.read_bytes()).decode("ascii")

out = HTML.replace("__DATA__", js).replace("__VIDEO__", video_b64)
(ROOT / "outputs" / "pong_academy_wedges.html").write_text(out)
print("Wrote outputs/pong_academy_wedges.html  (%.1f MB, video %.1f MB)"
      % (len(out) / 1048576, video_path.stat().st_size / 1048576))
print("Top 3:", [(w["id"], w["name"], w["scores"]["projected_score"]) for w in top3])
